In [5]:
import numpy as np
print(np.__version__)
print(np.array([1, 2, 3]))


1.24.3
[1 2 3]


In [6]:
##creating an array with numbers from 1-10 and then only printing the even numbers

In [7]:
num=np.arange(1,11)
for i in range(10):
    if num[i]%2 ==0:
        print (num[i])

2
4
6
8
10


In [8]:
##or a more professional way is by using boolean masking

In [9]:
even_nums=num[num%2==0]
print(even_nums)

[ 2  4  6  8 10]


In [10]:
##here you're basically asking a true or false question
##by using the boolean array
##so when you do this you're basically saying give me those elements of num where
##num %2==0  is true, and numpy masks out everything else thats false

In [11]:
##NOW SIMULATING 1000 DICE ROLLS, PRINT AVERAGE ROLLS AND STANDARD DEVIATION

In [12]:
rand100=np.random.randint(1,7,1000)
print(np.mean(rand100))
print(np.std(rand100))


3.348
1.710817348520876


In [13]:
##now creating a 3x3 random matrix and computing the sum of each row and column

In [14]:
matr3=np.random.rand(3,3)
print(np.sum(matr3,axis=0))
print(np.sum(matr3,axis=1))


[0.57828166 1.71588852 0.85344914]
[1.04952171 1.24014639 0.85795122]


In [15]:
## or to get proper integer random numbers instead of float
matr3_int=np.random.randint(0,10,size=(3,3))
print(np.sum(matr3_int,axis=0))
print(np.sum(matr3_int,axis=1))

[20 17 10]
[11 21 15]


In [18]:
##Reshape a 1D array of length 12 into a 3×4 matrix. and then print the first column

arr1=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_arr=arr1.reshape(3,4)
print(new_arr[0]) ##this gets the first row not the column
print(new_arr[:,0]) ##this means all rows, column 0


[1 2 3 4]
[1 5 9]
